In [150]:
import pandas as pd

# Load sample of delays, different train stations 
archivo_excel = "sample_delays.xlsx"

# reading all pages 
hojas = pd.read_excel(archivo_excel, sheet_name=None)

#iterating through each sheet and concatenating dataframes as well as adding new column with estation name
dataframes = []
for nombre_hoja, df in hojas.items():
    df["Estación"] = nombre_hoja  
    dataframes.append(df)


df_final = pd.concat(dataframes, ignore_index=True)


display(df_final)

,Hora de llegada,Origen,Tren,FECHA,Estación
0,09:08\n09:22,Castelló de la Plana,RF - AVE05069,2025-04-17,madrid
1,NaN,NaN,NaN,2025-04-17,madrid
2,09:36\n09:42,Sevilla Santa Justa,IL - IRYO06011,2025-04-17,madrid
3,NaN,NaN,NaN,2025-04-17,madrid
4,09:42:00,Barcelona Sants,IL - IRYO06270,2025-04-17,madrid
...,...,...,...,...,...
2637,23:48:00,Madrid Puerta de Atocha Almudena Grandes,RF - AVE03203,2025-04-16,barcelona
2638,NaN,NaN,NaN,2025-04-16,barcelona
2639,23:54:00,Madrid Puerta de Atocha Almudena Grandes,RI - OUIGO06611,2025-04-16,barcelona
2640,NaN,NaN,NaN,2025-04-16,barcelona
2641,23:59:00,Málaga María Zambrano,RF - AVE02783,2025-04-16,barcelona

In [151]:
# Renaming columns
df_final.rename(columns={
    "Hora de llegada": "arrival_time",
    "Origen": "origin",
    "Tren": "train",
    "FECHA": "date",
    "Estación": "train_station"
}, inplace=True)

#delegint rows with values NaN in arrival_time, origin, train
df_final.dropna(subset=["arrival_time", "origin", "train"], inplace=True)


display(df_final)

,arrival_time,origin,train,date,train_station
0,09:08\n09:22,Castelló de la Plana,RF - AVE05069,2025-04-17,madrid
2,09:36\n09:42,Sevilla Santa Justa,IL - IRYO06011,2025-04-17,madrid
4,09:42:00,Barcelona Sants,IL - IRYO06270,2025-04-17,madrid
6,09:45:00,Málaga María Zambrano,RF - AVE02063,2025-04-17,madrid
8,09:57:00,Pamplona / Iruña,RF - ALVIA00802,2025-04-17,madrid
...,...,...,...,...,...
2633,23:14:00,Madrid Puerta de Atocha Almudena Grandes,IL - IRYO06201,2025-04-16,barcelona
2635,23:47:00,Salou - Port Aventura,RF - RODALIES-R1715240,2025-04-16,barcelona
2637,23:48:00,Madrid Puerta de Atocha Almudena Grandes,RF - AVE03203,2025-04-16,barcelona
2639,23:54:00,Madrid Puerta de Atocha Almudena Grandes,RI - OUIGO06611,2025-04-16,barcelona
2641,23:59:00,Málaga María Zambrano,RF - AVE02783,2025-04-16,barcelona

In [152]:
# Filter the DataFrame to keep only relevant train types
train_keywords = ["AVLO", "AVE", "IRYO", "OUIGO"]
df_filtered = df_final[df_final["train"].str.contains("|".join(train_keywords), na=False, case=False)]

# Display the filtered DataFrame
display(df_filtered)

,arrival_time,origin,train,date,train_station
0,09:08\n09:22,Castelló de la Plana,RF - AVE05069,2025-04-17,madrid
2,09:36\n09:42,Sevilla Santa Justa,IL - IRYO06011,2025-04-17,madrid
4,09:42:00,Barcelona Sants,IL - IRYO06270,2025-04-17,madrid
6,09:45:00,Málaga María Zambrano,RF - AVE02063,2025-04-17,madrid
12,10:10\n10:46,Sevilla Santa Justa,RF - AVE02071,2025-04-17,madrid
...,...,...,...,...,...
2629,22:55:00,Madrid Puerta de Atocha Almudena Grandes,RF - AVLO06309,2025-04-16,barcelona
2633,23:14:00,Madrid Puerta de Atocha Almudena Grandes,IL - IRYO06201,2025-04-16,barcelona
2637,23:48:00,Madrid Puerta de Atocha Almudena Grandes,RF - AVE03203,2025-04-16,barcelona
2639,23:54:00,Madrid Puerta de Atocha Almudena Grandes,RI - OUIGO06611,2025-04-16,barcelona
2641,23:59:00,Málaga María Zambrano,RF - AVE02783,2025-04-16,barcelona

In [153]:
# Lista de compañías que quieres extraer
companies = ["AVE", "AVLO", "IRYO", "OUIGO"]

def extract_company(train):
    for company in companies:
        if company in train:
            return company
    return None  

# Crear la nueva columna aplicando la función
df_filtered["company"] = df_filtered["train"].apply(extract_company)

display(df_filtered.sample(10))

C:\Users\maria.aguilar\AppData\Local\Temp\ipykernel_7500\1368527089.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtered["company"] = df_filtered["train"].apply(extract_company)

,arrival_time,origin,train,date,train_station,company
1033,17:05:00,Madrid Puerta de Atocha Almudena Grandes,RI - OUIGO06566,2025-04-19,cordoba,OUIGO
885,20:16:00,Barcelona Sants,RF - AVE03942,2025-04-17,cordoba,AVE
2218,20:46:00,Madrid Puerta de Atocha Almudena Grandes,RF - AVE03175,2025-04-19,barcelona,AVE
1346,17:56:00,Madrid Puerta de Atocha Almudena Grandes,RF - AVLO02156,2025-04-17,sevilla,AVLO
2182,19:19:00,Madrid Puerta de Atocha Almudena Grandes,RF - AVE03163,2025-04-19,barcelona,AVE
101,15:52:00,Marseille Saint Charles,RF - AVE09730,2025-04-17,madrid,AVE
840,18:28:00,Sevilla Santa Justa,RF - AVE02171,2025-04-17,cordoba,AVE
61,13:15:00,Sevilla Santa Justa,RF - AVE02101,2025-04-17,madrid,AVE
1830,16:49:00,Madrid Puerta de Atocha Almudena Grandes,RI - OUIGO06541,2025-04-17,barcelona,OUIGO
1507,10:25:00,Madrid Puerta de Atocha Almudena Grandes,RI - OUIGO06476,2025-04-16,sevilla,OUIGO

In [154]:

display(df_filtered.sample(10))

,arrival_time,origin,train,date,train_station,company
1340,16:37:00,Madrid Puerta de Atocha Almudena Grandes,IL - IRYO06136,2025-04-17,sevilla,IRYO
466,10:38\n10:43,Huesca,RF - AVE03872,2025-04-16,madrid,AVE
1830,16:49:00,Madrid Puerta de Atocha Almudena Grandes,RI - OUIGO06541,2025-04-17,barcelona,OUIGO
2022,11:19:00,Madrid Puerta de Atocha Almudena Grandes,RF - AVE03083,2025-04-19,barcelona,AVE
801,16:26:00,Sevilla Santa Justa,RF - AVE02861,2025-04-17,cordoba,AVE
1880,18:46:00,Madrid Puerta de Atocha Almudena Grandes,RF - AVLO06305,2025-04-17,barcelona,AVLO
307,13:52:00,Barcelona Sants,RF - AVE03112,2025-04-17,madrid,AVE
1791,15:14:00,Madrid Puerta de Atocha Almudena Grandes,IL - IRYO06121,2025-04-17,barcelona,IRYO
400,20:50:00,Sevilla Santa Justa,IL - IRYO06177,2025-04-17,madrid,IRYO
239,09:17:00,Barcelona Sants,RI - OUIGO06470,2025-04-17,madrid,OUIGO

In [155]:
# Función para separar los timestamps
def process_arrival_time(arrival_time):
    arrival_time = str(arrival_time)  # Convertir a cadena por si es datetime.time
    tiempos = arrival_time.split("\n")  # Separar por salto de línea
    return tiempos[0], tiempos[-1]  # Primer timestamp en arrival_time, último en real_arrival_time

# Aplicar la función asegurando que arrival_time es una cadena
df_filtered["arrival_time"], df_filtered["real_arrival_time"] = zip(*df_filtered["arrival_time"].astype(str).apply(process_arrival_time))

# Mostrar los primeros registros para comprobar
display(df_filtered.sample(10))

C:\Users\maria.aguilar\AppData\Local\Temp\ipykernel_7500\3738835658.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtered["arrival_time"], df_filtered["real_arrival_time"] = zip(*df_filtered["arrival_time"].astype(str).apply(process_arrival_time))
C:\Users\maria.aguilar\AppData\Local\Temp\ipykernel_7500\3738835658.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtered["arrival_time"], df_filtered["real_arrival_time"] = zip(*df_filtered["arrival_time"].astype(str).apply(process_arrival_time))

,arrival_time,origin,train,date,train_station,company,real_arrival_time
2259,22:33:00,Sevilla Santa Justa,RF - AVE03941,2025-04-19,barcelona,AVE,22:33:00
1105,20:36:00,Madrid Puerta de Atocha Almudena Grandes,RF - AVLO02188,2025-04-19,cordoba,AVLO,20:36:00
1911,19:54:00,Madrid Puerta de Atocha Almudena Grandes,RI - OUIGO06571,2025-04-17,barcelona,OUIGO,19:54:00
1039,17:18:00,Sevilla Santa Justa,RF - AVE03941,2025-04-19,cordoba,AVE,17:18:00
1334,15:47:00,Barcelona Sants,IL - IRYO06010,2025-04-17,sevilla,IRYO,15:47:00
1406,11:56:00,Madrid Puerta de Atocha Almudena Grandes,RF - AVLO02096,2025-04-19,sevilla,AVLO,11:56:00
2637,23:48:00,Madrid Puerta de Atocha Almudena Grandes,RF - AVE03203,2025-04-16,barcelona,AVE,23:48:00
1099,20:16:00,Barcelona Sants,RF - AVE03992,2025-04-19,cordoba,AVE,20:16:00
605,19:52:00,Barcelona Sants,RF - AVE03172,2025-04-16,madrid,AVE,19:52:00
793,16:18:00,Málaga María Zambrano,IL - IRYO06159,2025-04-17,cordoba,IRYO,16:18:00

In [156]:
# Crear la nueva columna comparando arrival_time y real_arrival_time
df_filtered["status"] = df_filtered.apply(lambda row: "delayed" if row["arrival_time"] != row["real_arrival_time"] else "on time", axis=1)

# Mostrar los primeros registros para comprobar
display(df_filtered.sample(10))

C:\Users\maria.aguilar\AppData\Local\Temp\ipykernel_7500\3181820669.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtered["status"] = df_filtered.apply(lambda row: "delayed" if row["arrival_time"] != row["real_arrival_time"] else "on time", axis=1)

,arrival_time,origin,train,date,train_station,company,real_arrival_time,status
555,16:37:00,Barcelona Sants,IL - IRYO06014,2025-04-16,madrid,IRYO,16:37:00,on time
541,15:52:00,Marseille Saint Charles,RF - AVE09730,2025-04-16,madrid,AVE,15:52:00,on time
97,15:12:00,Sevilla Santa Justa,RF - AVE02121,2025-04-17,madrid,AVE,15:12:00,on time
263,10:38:00,Huesca,RF - AVE03872,2025-04-17,madrid,AVE,10:38:00,on time
916,21:36:00,Sevilla Santa Justa,RF - AVLO02217,2025-04-17,cordoba,AVLO,21:36:00,on time
1583,18:02,Madrid Puerta de Atocha Almudena Grandes,RI - OUIGO06566,2025-04-16,sevilla,OUIGO,18:08,delayed
2629,22:55:00,Madrid Puerta de Atocha Almudena Grandes,RF - AVLO06309,2025-04-16,barcelona,AVLO,22:55:00,on time
2477,17:41,Málaga María Zambrano,IL - IRYO06021,2025-04-16,barcelona,IRYO,17:52,delayed
2429,15:44:00,Madrid Puerta de Atocha Almudena Grandes,RF - AVE03123,2025-04-16,barcelona,AVE,15:44:00,on time
1558,15:43:00,Madrid Puerta de Atocha Almudena Grandes,RF - AVE02130,2025-04-16,sevilla,AVE,15:43:00,on time

In [157]:
import scipy.stats as stats
# Filtrar por compañías
renfe = df_filtered[df_filtered['company'].isin(["AVE", "AVLO"])]
otras = df_filtered[df_filtered['company'].isin(["IRYO", "OUIGO"])]

# Calcular proporción de puntualidad
p_renfe = (renfe['status'] == "on time").sum() / len(renfe)
p_otras = (otras['status'] == "on time").sum() / len(otras)

# Prueba de proporciones
n_renfe = len(renfe)
n_otras = len(otras)

prop_test = stats.ttest_ind(renfe['status'] == "on time", otras['status'] == "on time")

print(f"RENFE puntualidad: {p_renfe:.2f}")
print(f"Otras compañías puntualidad: {p_otras:.2f}")
print("Prueba de hipótesis:", prop_test)

RENFE puntualidad: 0.87
Otras compañías puntualidad: 0.91
Prueba de hipótesis: TtestResult(statistic=-1.431136655931386, pvalue=0.15289489538133771, df=620.0)

In [158]:
import scipy.stats as stats
# Filtrar por compañías
renfe = df_filtered[df_filtered['company'].isin(["AVE", "AVLO"])]
iryo = df_filtered[df_filtered['company'].isin(["IRYO"])]

# Calcular proporción de puntualidad
p_renfe = (renfe['status'] == "on time").sum() / len(renfe)
p_iryo = (iryo['status'] == "on time").sum() / len(iryo)

# Prueba de proporciones
n_renfe = len(renfe)
n_iryo = len(iryo)

prop_test = stats.ttest_ind(renfe['status'] == "on time", iryo['status'] == "on time")

print(f"RENFE puntualidad: {p_renfe:.2f}")
print(f"IRYO puntualidad: {p_iryo:.2f}")
print("Prueba de hipótesis:", prop_test)

RENFE puntualidad: 0.87
IRYO puntualidad: 0.91
Prueba de hipótesis: TtestResult(statistic=-1.3387025000850925, pvalue=0.1812126848101605, df=558.0)

In [159]:
import scipy.stats as stats

renfe = df_filtered[df_filtered['company'].isin(["AVLO"])]
ouigo = df_filtered[df_filtered['company'].isin(["OUIGO"])]


p_renfe = (renfe['status'] == "on time").sum() / len(renfe)
p_ouigo = (ouigo['status'] == "on time").sum() / len(ouigo)

n_renfe = len(renfe)
n_ouigo = len(iryo)

prop_test = stats.ttest_ind(renfe['status'] == "on time", ouigo['status'] == "on time")

print(f"RENFE puntualidad: {p_renfe:.2f}")
print(f"OUIGO puntualidad: {p_ouigo:.2f}")
print("Prueba de hipótesis:", prop_test)

RENFE puntualidad: 0.91
OUIGO puntualidad: 0.90
Prueba de hipótesis: TtestResult(statistic=0.08533910747013992, pvalue=0.9321283376444109, df=125.0)

In [165]:
df = df_filtered.copy()

In [ ]:
# Convertir la columna date a datetime
df["date"] = pd.to_datetime(df["date"], format="%Y-%m-%d")

# Agregar ":00" a los valores de tiempo si no tienen segundos
df["arrival_time"] = df["arrival_time"].apply(lambda x: x if len(x) == 8 else x + ":00")
df["real_arrival_time"] = df["real_arrival_time"].apply(lambda x: x if len(x) == 8 else x + ":00")

# Convertir a datetime 
df["arrival_time"] = pd.to_datetime(df["date"].astype(str) + " " + df["arrival_time"], format="%Y-%m-%d %H:%M:%S", errors="coerce")
df["real_arrival_time"] = pd.to_datetime(df["date"].astype(str) + " " + df["real_arrival_time"], format="%Y-%m-%d %H:%M:%S", errors="coerce")

# Calcular el retraso en minutos
df["delay_minutes"] = (df["real_arrival_time"] - df["arrival_time"]).dt.total_seconds() / 60

In [170]:
df.sample(10)

,arrival_time,origin,train,date,train_station,company,real_arrival_time,status,delay_minutes
2243,2025-04-19 21:58:00,Granada,RF - AVE03931,2025-04-19,barcelona,AVE,2025-04-19 21:58:00,on time,0.0
245,2025-04-17 09:36:00,Sevilla Santa Justa,IL - IRYO06011,2025-04-17,madrid,IRYO,2025-04-17 09:36:00,on time,0.0
631,2025-04-16 21:52:00,Figueres-Vilafant,RF - AVE03192,2025-04-16,madrid,AVE,2025-04-16 21:52:00,on time,0.0
1366,2025-04-17 19:56:00,Madrid Puerta de Atocha Almudena Grandes,RF - AVLO02176,2025-04-17,sevilla,AVLO,2025-04-17 19:56:00,on time,0.0
539,2025-04-16 15:30:00,Barcelona Sants,IL - IRYO11870,2025-04-16,madrid,IRYO,2025-04-16 15:30:00,on time,0.0
557,2025-04-16 16:42:00,Sevilla Santa Justa,IL - IRYO06147,2025-04-16,madrid,IRYO,2025-04-16 16:42:00,on time,0.0
2196,2025-04-19 19:54:00,Madrid Puerta de Atocha Almudena Grandes,RI - OUIGO06571,2025-04-19,barcelona,OUIGO,2025-04-19 19:54:00,on time,0.0
31,2025-04-17 11:02:00,Barcelona Sants,RF - AVE03080,2025-04-17,madrid,AVE,2025-04-17 11:02:00,on time,0.0
957,2025-04-19 12:36:00,Madrid Puerta de Atocha Almudena Grandes,RF - AVLO02108,2025-04-19,cordoba,AVLO,2025-04-19 12:36:00,on time,0.0
1733,2025-04-17 13:04:00,Madrid Puerta de Atocha Almudena Grandes,RI - OUIGO06501,2025-04-17,barcelona,OUIGO,2025-04-17 13:38:00,delayed,34.0

In [171]:
# Prueba Chi-cuadrado para ver si la compañía afecta la puntualidad
contingency_table = pd.crosstab(df["company"], df["status"])
chi2_stat, p_chi2, dof, expected = stats.chi2_contingency(contingency_table)

print("📌 Prueba Chi-cuadrado:")
print(f"Chi2 statistic: {chi2_stat:.2f}, p-value: {p_chi2:.5f}")

📌 Prueba Chi-cuadrado:
Chi2 statistic: 3.16, p-value: 0.36739

In [175]:
# 2️⃣ Prueba t para comparar tiempos de retraso entre RENFE (AVE + AVLO) vs. otras compañías
renfe_delays = df.loc[df["company"].isin(["AVE", "AVLO"]), "delay_minutes"]
otras_delays = df.loc[df["company"].isin(["IRYO", "OUIGO"]), "delay_minutes"]

t_stat, p_ttest = stats.ttest_ind(renfe_delays, otras_delays, equal_var=False)  # Test de comparación de medias

print("\n📌 T-test for delay comparison")
print(f"t-statistic: {t_stat:.2f}, p-value: {p_ttest:.5f}")

#Since the p-value is less than 0.05, we can conclude that there is a statistically significant difference between the delays of RENFE (AVE + AVLO) 
# and those of IRYO + OUIGO. That is, RENFE's delay times are significantly different from those of the other companies.

📌 T-test for delay comparison
t-statistic: 2.08, p-value: 0.03804

In [174]:
delayed_trains = df[df["status"] == "delayed"]

print(delayed_trains.groupby("company")["delay_minutes"].mean())

company
AVE      18.886364
AVLO     15.166667
IRYO      7.875000
OUIGO    12.166667
Name: delay_minutes, dtype: float64